Repository sonia-auv/provider_kill_mission, pull requests merged in 2020-07, with the labels that each got.

#16 Feature/refactor workflows again
  .github/workflows/docker-image-develop.yml
  .github/workflows/docker-image-feature.yml
  .github/workflows/docker-image-master.yml
  .github/workflows/docker-image-robot-develop.yml
  .github/workflows/docker-image-robot-feature.yml
  .github/workflows/docker-image-robot-master.yml
  Dockerfile
  Dockerfile-arm64
  Dockerfile-x86-64
  package.xml
  scripts/sonia_entrypoint.sh
Labels: Priority: High, Type: Feature

#14 Add folders to dockerignore file
  .dockerignore
Labels: Priority: High, Type: Feature

#18 Feature/fix develop 1.0.8
  .github/workflows/docker-image-robot-develop.yml
  .github/workflows/docker-image-robot-feature.yml
  .github/workflows/docker-image-robot-master.yml
  Dockerfile
Labels: Priority: Critical, Type: Bug

#17 Develop
  .dockerignore
  .github/workflows/docker-image-develop.yml
  .github/workflows/docker-image-feature.yml
  .github/workflows/docker-image-master.yml
  .github/workflows/docker-image-robot-develop.yml
  .github/workflows/docker-image-robot-feature.yml
  .github/workflows/docker-image-robot-master.yml
  .gitignore
  CMakeLists.txt
  Dockerfile
  msg/KillSwitchMsg.msg
  msg/MissionSwitchMsg.msg
  package.xml
  scripts/sonia_entrypoint.sh
  src/provider_kill_mission/provider_kill_mission_node.cc
  src/provider_kill_mission/provider_kill_mission_node.h
  srv/GetKillSwitch.srv
  srv/GetMissionSwitch.srv
  srv/GetOverrideMissionSwitch.srv
  srv/OverrideMissionSwitch.srv
  srv/SetMissionSwitch.srv
Labels: Priority: High, Type: Enhancement

#19 Feature/fix dockerfile
  Dockerfile
  package.xml
Labels: Priority: Critical, Type: Bug

#21 Feature/add remote container development
  .devcontainer/devcontainer.json
  .dockerignore
  .vscode/c_cpp_properties.json
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
  Dockerfile
  LICENCE
  README.md
  package.xml
Labels: Priority: High, Type: Enhancement
