Repository sonia-auv/provider_kill_mission, pull requests merged in 2022-05, with the labels that each got.

#34 Fix/update actions
  .github/workflows/docker-image-perception-develop.yml
  .github/workflows/docker-image-perception-feature.yml
  .github/workflows/docker-image-perception-fix.yml
Labels: Priority: High, Type: Feature

#35 Develop
  .github/ISSUE_TEMPLATE/config.yml
  .github/workflows/docker-image-perception-develop.yml
  .github/workflows/docker-image-perception-feature.yml
  .github/workflows/docker-image-perception-fix.yml
  .github/workflows/docker-image-perception-master.yml
  .vscode/settings.json
  CMakeLists.txt
  Dockerfile
  package.xml
  setup.py
  src/provider_kill_mission/provider_kill_mission_node.cc
  src/provider_kill_mission/provider_kill_mission_node.h
Labels: Priority: Medium, Type: Feature

#36 Feature/latch
  .github/pull_request_template.md
  package.xml
  src/provider_kill_mission/provider_kill_mission_node.cc
Labels: Priority: Low, Type: Enhancement
